version: "3"

services:
    app:
        build:
            context: .
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c " python manage.py wait_for_db && 
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    python manage.py runserver 0.0.0.0:8000"
        env_file:
            - .env
        environment:
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_ROOT_PASS}
            - DB_PORT=${DB_OUTSIDE_PORT} 
            - SECRET_KEY=${SECRET_KEY}
            - TZ=${TIME_ZONE}
        depends_on:
            - db
        links: # Link to containers in another service.
            - db:db
    db:
        image: mysql:8.0.15
        env_file:
            - .env
        restart: always
        ports:
            - ${DB_OUTSIDE_PORT}:${DB_PORT}
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
            - TZ=${TIME_ZONE}
        volumes:
            - ./mysql_data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            # - ./mysql_data/init.sql:/data/application/init.sql
            - ./mysql_data/mysql:/var/lib/mysql
            - ./mysql_data/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        # command: --init-file /data/application/init.sql
